[RFC] Add command in bin for clearing cache even if environment is broken
symfony/symfony-standard pull request #1105
Opened 2017-07-29 10:59 UTC by curry684

Follows the discussion at https://github.com/symfony/symfony/issues/23592

This command allows one to run `bin/clear-cache` or `bin/clear-cache <envName>` in any situation. It's consciously implemented als Plain Ole PHP since it is most commonly used to fix a temporary broken environment, in which the vendor directory or its packages may also well be (temporarily) broken. So no use in depending on `symfony/console` or 'symfony/process`.

If we do this the `clearCache` command in SensioDistributionBundle will also need to be patched afterwards, and some documentation changed.

Based on 3.3 as it deprecated `clear:cache` without `--no-warmup`, no use in adding it to older versions.

2017-07-29 16:29 UTC, theofidry commented
I think this can be done in the Makefile if not already done tbh

2017-07-31 17:09 UTC, ostrolucky requested changes
This script is too stupid:
- assumes composer.json is in same dir
- doesn't handle paths overridden via AppKernel
- doesn't return correct exit codes
- uses system call instead of unlink
- hardcoded path and newline separators
- untestable
- if system call fails, script outputs bogus success message

I suggest not doing anything until fortune of cache:clear is decided

2017-07-31 19:52 UTC, curry684 commented
@ostrolucky most of those comments are intentional of course.

- There is no assumption about the location of the composer.json. It is used if you have a "normal" install. Otherwise we can find nor use it.
- The use case for the script is being able to restore broken installs. No external dependencies, so no AppKernel loading. If you have a "normal" install, it works. If you don't, it won't. But the same goes for `bin/console` and we keep that in there in the default installl.
- The use of system commands is intentional, as it provides much more reasonable output than recursive `unlink` will ever give (think read-only filesystems etc.). Admittedly I don't think that output is currently being piped correctly, and you're right about the exit codes.
- The path and newline separators do not matter. PHP is well documented since somewhere in the 4.x era to be agnostic to them. Using `DIRECTORY_SEPARATOR` in paths and `PHP_EOL` in console output has no added value therefore, they're only useful for example in *parsing* local paths and writing platform-specific file formats.
- The `bin/console` script is just as (un)testable.

2017-07-31 21:06 UTC, Pierstoval commented
Adding such script just for one uncommon use-case is a total mess. There are workarounds for symfony/symfony#23592, and implementing this kind of logic rough and tough like that just lacks understanding of how Symfony works... 😕

2017-08-01 08:43 UTC, curry684 commented
The workaround appears to be `rm -rf` according to https://github.com/symfony/symfony/issues/23592#issuecomment-318627886. I know it's rough and tough, but it's a PR in Symfony Standard Edition, not Symfony core. It doesn't matter that you can break it by going power-user in Symfony, as that will break more scripts, including potentially `bin/console` itself.

Anyway, if the discussion is going to the level of implying I don't understand how Symfony works I'll just close and we'll keep advising people to `rm -rf`.

2017-08-01 08:43 UTC, closed without merging